# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created: Wed Jul 24 20:10:10 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(922, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/FAX.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.verticalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(36, 36))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 922, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_System = QtGui.QMenu(self.menuBar)
        self.menu_System.setObjectName(_fromUtf8("menu_System"))
        self.menu_Delivery = QtGui.QMenu(self.menuBar)
        self.menu_Delivery.setObjectName(_fromUtf8("menu_Delivery"))
        self.menu_Receipt = QtGui.QMenu(self.menuBar)
        self.menu_Receipt.setObjectName(_fromUtf8("menu_Receipt"))
        self.menu_Meta = QtGui.QMenu(self.menuBar)
        self.menu_Meta.setObjectName(_fromUtf8("menu_Meta"))
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menu_Report = QtGui.QMenu(self.menuBar)
        self.menu_Report.setObjectName(_fromUtf8("menu_Report"))
        MainWindow.setMenuBar(self.menuBar)
        self.action_Backup = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_135_inbox_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Backup.setIcon(icon1)
        self.action_Backup.setObjectName(_fromUtf8("action_Backup"))
        self.action_Restore = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_134_inbox_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Restore.setIcon(icon2)
        self.action_Restore.setObjectName(_fromUtf8("action_Restore"))
        self.action_Changepassword = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_240_rotation_lock.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Changepassword.setIcon(icon3)
        self.action_Changepassword.setObjectName(_fromUtf8("action_Changepassword"))
        self.action_Exit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_063_power.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon4)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_Deliver = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_208_cart_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Deliver.setIcon(icon5)
        self.action_Deliver.setObjectName(_fromUtf8("action_Deliver"))
        self.action_Return = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_209_cart_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Return.setIcon(icon6)
        self.action_Return.setObjectName(_fromUtf8("action_Return"))
        self.action_DeliveryRecords = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_114_list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_DeliveryRecords.setIcon(icon7)
        self.action_DeliveryRecords.setObjectName(_fromUtf8("action_DeliveryRecords"))
        self.action_DeliverySummarize = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_119_table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_DeliverySummarize.setIcon(icon8)
        self.action_DeliverySummarize.setObjectName(_fromUtf8("action_DeliverySummarize"))
        self.action_Receipt = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_227_usd.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Receipt.setIcon(icon9)
        self.action_Receipt.setObjectName(_fromUtf8("action_Receipt"))
        self.action_ReceiptSummarize = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_325_wallet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ReceiptSummarize.setIcon(icon10)
        self.action_ReceiptSummarize.setObjectName(_fromUtf8("action_ReceiptSummarize"))
        self.action_ReceiptSheet = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_087_log_book.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ReceiptSheet.setIcon(icon11)
        self.action_ReceiptSheet.setObjectName(_fromUtf8("action_ReceiptSheet"))
        self.action_Customers = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_024_parents.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Customers.setIcon(icon12)
        self.action_Customers.setObjectName(_fromUtf8("action_Customers"))
        self.action_Products = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_149_folder_new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Products.setIcon(icon13)
        self.action_Products.setObjectName(_fromUtf8("action_Products"))
        self.action_Employees = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_043_group.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Employees.setIcon(icon14)
        self.action_Employees.setObjectName(_fromUtf8("action_Employees"))
        self.action_DeliveryReport = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_036_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_DeliveryReport.setIcon(icon15)
        self.action_DeliveryReport.setObjectName(_fromUtf8("action_DeliveryReport"))
        self.action_ReceiptReport = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_323_calculator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ReceiptReport.setIcon(icon16)
        self.action_ReceiptReport.setObjectName(_fromUtf8("action_ReceiptReport"))
        self.action_DataImport = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_221_unshare.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_DataImport.setIcon(icon17)
        self.action_DataImport.setObjectName(_fromUtf8("action_DataImport"))
        self.action_DataExport = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_222_share.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_DataExport.setIcon(icon18)
        self.action_DataExport.setObjectName(_fromUtf8("action_DataExport"))
        self.action_ReceiptRecords = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_113_justify.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ReceiptRecords.setIcon(icon19)
        self.action_ReceiptRecords.setObjectName(_fromUtf8("action_ReceiptRecords"))
        self.action_About = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/glyphicons_195_circle_info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_About.setIcon(icon20)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.toolBar.addAction(self.action_Deliver)
        self.toolBar.addAction(self.action_Return)
        self.toolBar.addAction(self.action_Receipt)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_DeliveryRecords)
        self.toolBar.addAction(self.action_DeliverySummarize)
        self.toolBar.addAction(self.action_ReceiptRecords)
        self.toolBar.addAction(self.action_ReceiptSummarize)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_DeliveryReport)
        self.toolBar.addAction(self.action_ReceiptReport)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Customers)
        self.toolBar.addAction(self.action_Products)
        self.toolBar.addAction(self.action_Employees)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Exit)
        self.menu_System.addAction(self.action_Backup)
        self.menu_System.addAction(self.action_Restore)
        self.menu_System.addSeparator()
        self.menu_System.addAction(self.action_DataImport)
        self.menu_System.addAction(self.action_DataExport)
        self.menu_System.addSeparator()
        self.menu_System.addAction(self.action_Changepassword)
        self.menu_System.addSeparator()
        self.menu_System.addAction(self.action_Exit)
        self.menu_Delivery.addAction(self.action_Deliver)
        self.menu_Delivery.addAction(self.action_Return)
        self.menu_Delivery.addSeparator()
        self.menu_Delivery.addAction(self.action_DeliveryRecords)
        self.menu_Delivery.addAction(self.action_DeliverySummarize)
        self.menu_Receipt.addAction(self.action_Receipt)
        self.menu_Receipt.addSeparator()
        self.menu_Receipt.addAction(self.action_ReceiptSummarize)
        self.menu_Receipt.addAction(self.action_ReceiptSheet)
        self.menu_Meta.addAction(self.action_Customers)
        self.menu_Meta.addAction(self.action_Products)
        self.menu_Meta.addAction(self.action_Employees)
        self.menu_Help.addAction(self.action_About)
        self.menu_Report.addAction(self.action_DeliveryReport)
        self.menu_Report.addAction(self.action_ReceiptReport)
        self.menuBar.addAction(self.menu_System.menuAction())
        self.menuBar.addAction(self.menu_Delivery.menuAction())
        self.menuBar.addAction(self.menu_Receipt.menuAction())
        self.menuBar.addAction(self.menu_Meta.menuAction())
        self.menuBar.addAction(self.menu_Report.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.menu_System.setTitle(_translate("MainWindow", "系统 (&S)", None))
        self.menu_Delivery.setTitle(_translate("MainWindow", "发货 (&D)", None))
        self.menu_Receipt.setTitle(_translate("MainWindow", "收款 (&F)", None))
        self.menu_Meta.setTitle(_translate("MainWindow", "基础资料 (&M)", None))
        self.menu_Help.setTitle(_translate("MainWindow", "帮助 (&H)", None))
        self.menu_Report.setTitle(_translate("MainWindow", "报表(&R)", None))
        self.action_Backup.setText(_translate("MainWindow", "备份数据", None))
        self.action_Backup.setShortcut(_translate("MainWindow", "Ctrl+Alt+S", None))
        self.action_Restore.setText(_translate("MainWindow", "恢复数据", None))
        self.action_Restore.setShortcut(_translate("MainWindow", "Ctrl+Alt+O", None))
        self.action_Changepassword.setText(_translate("MainWindow", "更改密码", None))
        self.action_Exit.setText(_translate("MainWindow", "退出程序", None))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+Alt+Q", None))
        self.action_Deliver.setText(_translate("MainWindow", "发货", None))
        self.action_Deliver.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.action_Return.setText(_translate("MainWindow", "退货", None))
        self.action_Return.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.action_DeliveryRecords.setText(_translate("MainWindow", "发货记录", None))
        self.action_DeliverySummarize.setText(_translate("MainWindow", "发货汇总", None))
        self.action_Receipt.setText(_translate("MainWindow", "收款", None))
        self.action_Receipt.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_ReceiptSummarize.setText(_translate("MainWindow", "收款汇总", None))
        self.action_ReceiptSheet.setText(_translate("MainWindow", "对账", None))
        self.action_Customers.setText(_translate("MainWindow", "客户资料", None))
        self.action_Customers.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.action_Products.setText(_translate("MainWindow", "产品资料", None))
        self.action_Products.setToolTip(_translate("MainWindow", "产品资料", None))
        self.action_Products.setShortcut(_translate("MainWindow", "Ctrl+G", None))
        self.action_Employees.setText(_translate("MainWindow", "业务资料", None))
        self.action_Employees.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.action_DeliveryReport.setText(_translate("MainWindow", "发货报表", None))
        self.action_ReceiptReport.setText(_translate("MainWindow", "应收报表", None))
        self.action_DataImport.setText(_translate("MainWindow", "数据导入", None))
        self.action_DataExport.setText(_translate("MainWindow", "数据导出", None))
        self.action_ReceiptRecords.setText(_translate("MainWindow", "收款记录", None))
        self.action_ReceiptRecords.setToolTip(_translate("MainWindow", "收款记录", None))
        self.action_About.setText(_translate("MainWindow", "关于", None))

import resource_rc
